### ISSUE TITLE
dependency problem

### ISSUE THREAD

**Issue by enricopesce** [dylburger/create-and-validate-acm-certificate#2]
Hi 

I've installed the package in my venv (python 3.6) by pip and after I tried the setup.py but i have this error in every case:

  File "/Users/enrico.pesce/git/pixartprinting/pixartprinting.aws/REDIRECTS/templates/certificates.py", line 3, in <module>
    from acm_factory import DNSValidatedACMCertClient
  File "/Users/enrico.pesce/git/pixartprinting/pixartprinting.aws/REDIRECTS/venv/lib/python3.6/site-packages/acm_factory-0.1-py3.6.egg/acm_factory/__init__.py", line 1, in <module>
    from ACM import DNSValidatedACMCertClient
ModuleNotFoundError: No module named 'ACM'

**Comment by dylburger** [comment]
@enricopesce sorry for the delay, was away from keyboard for the weekend. 

Just to confirm, are you having trouble installing the package, or trying to create a new certificate?

I'm able to install the package by creating a new virtual environment and running:

    pip install git+https://github.com/dylburger/create-and-validate-acm-certificate

If you're having trouble with something else, can you copy the exact line of code you're trying to run and share it here?
